;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-visual-line
	end-of-buffer
	end-of-visual-line
	hungry-delete-backward
	hungry-delete-forward
	kill-visual-line
	org-force-self-insert
	org-metaright
	org-return
	org-self-insert-command
	org-yank
	text-scale-adjust
	))

(setq mc/cmds-to-run-once
      '(
	amx
	org-cycle-agenda-files
	))
