;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-visual-line
	crux-move-beginning-of-line
	end-of-buffer
	end-of-visual-line
	hungry-delete-backward
	hungry-delete-forward
	indent-for-tab-command
	kill-region
	kill-visual-line
	move-line-down
	org-ctrl-c-ctrl-c
	org-force-self-insert
	org-metadown
	org-metaleft
	org-metaright
	org-refile
	org-return
	org-self-insert-command
	org-shiftright
	org-todo
	org-yank
	text-scale-adjust
	))

(setq mc/cmds-to-run-once
      '(
	amx
	mouse-set-region
	org-cycle
	org-cycle-agenda-files
	sp-remove-active-pair-overlay
	switch-window
	))
